//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIF2Entities : DbContext
    {
        public LIF2Entities()
            : base("name=LIF2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<effect> effects { get; set; }
        public virtual DbSet<effects_sets> effects_sets { get; set; }
        public virtual DbSet<objects_types> objects_types { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<recipe_possible_blueprints> recipe_possible_blueprints { get; set; }
        public virtual DbSet<recipe_requirement> recipe_requirement { get; set; }
        public virtual DbSet<skill_type> skill_type { get; set; }
    }
}
