//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class effect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public effect()
        {
            this.effects_sets = new HashSet<effects_sets>();
            this.effects_sets1 = new HashSet<effects_sets>();
            this.effects_sets2 = new HashSet<effects_sets>();
        }
    
        public short ID { get; set; }
        public string Effect_name { get; set; }
        public Nullable<int> ResultPreparationID { get; set; }
        public Nullable<int> ResultPotionID { get; set; }
        public Nullable<short> PlayerEffectID { get; set; }
    
        public virtual objects_types objects_types { get; set; }
        public virtual objects_types objects_types1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<effects_sets> effects_sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<effects_sets> effects_sets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<effects_sets> effects_sets2 { get; set; }
    }
}
