//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public objects_types()
        {
            this.effects = new HashSet<effect>();
            this.effects1 = new HashSet<effect>();
            this.recipe_requirement = new HashSet<recipe_requirement>();
            this.recipes = new HashSet<recipe>();
            this.recipes1 = new HashSet<recipe>();
            this.objects_types1 = new HashSet<objects_types>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public short IsContainer { get; set; }
        public short IsMovableObject { get; set; }
        public short IsUnmovableobject { get; set; }
        public short IsTool { get; set; }
        public short IsDevice { get; set; }
        public short IsDoor { get; set; }
        public Nullable<int> MaxContSize { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<int> MaxStackSize { get; set; }
        public Nullable<int> UnitWeight { get; set; }
        public string BackgndImage { get; set; }
        public Nullable<short> WorkAreaTop { get; set; }
        public Nullable<short> WorkAreaLeft { get; set; }
        public Nullable<short> WorkAreaWidth { get; set; }
        public Nullable<short> WorkAreaHeight { get; set; }
        public Nullable<short> BtnCloseTop { get; set; }
        public Nullable<short> BtnCloseLeft { get; set; }
        public string FaceImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> BasePrice { get; set; }
        public Nullable<int> OwnerTimeout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<effect> effects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<effect> effects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_requirement> recipe_requirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe> recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe> recipes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objects_types> objects_types1 { get; set; }
        public virtual objects_types objects_types2 { get; set; }
    }
}
