//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.recipe_possible_blueprints = new HashSet<recipe_possible_blueprints>();
            this.recipe_possible_blueprints1 = new HashSet<recipe_possible_blueprints>();
            this.recipe_requirement = new HashSet<recipe_requirement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StartingToolsID { get; set; }
        public Nullable<int> SkillTypeID { get; set; }
        public Nullable<short> SkillLvl { get; set; }
        public Nullable<int> ResultObjectTypeID { get; set; }
        public short SkillDepends { get; set; }
        public short Quantity { get; set; }
        public short Autorepeat { get; set; }
        public short IsBlueprint { get; set; }
    
        public virtual objects_types objects_types { get; set; }
        public virtual objects_types objects_types1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_possible_blueprints> recipe_possible_blueprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_possible_blueprints> recipe_possible_blueprints1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_requirement> recipe_requirement { get; set; }
        public virtual skill_type skill_type { get; set; }
    }
}
