CREATE TABLE [dbo].[objects_types] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL,
    [ParentID]          INT           DEFAULT (NULL) NULL,
    [Name]              VARCHAR (45)  DEFAULT ('') NOT NULL,
    [IsContainer]       SMALLINT      DEFAULT ('0') NOT NULL,
    [IsMovableObject]   SMALLINT      DEFAULT ('0') NOT NULL,
    [IsUnmovableobject] SMALLINT      DEFAULT ('0') NOT NULL,
    [IsTool]            SMALLINT      DEFAULT ('0') NOT NULL,
    [IsDevice]          SMALLINT      DEFAULT ('0') NOT NULL,
    [IsDoor]            SMALLINT      DEFAULT ('0') NOT NULL,
    [MaxContSize]       INT           DEFAULT (NULL) NULL,
    [Length]            SMALLINT      DEFAULT (NULL) NULL,
    [MaxStackSize]      INT           DEFAULT (NULL) NULL,
    [UnitWeight]        INT           DEFAULT (NULL) NULL,
    [BackgndImage]      VARCHAR (250) DEFAULT (NULL) NULL,
    [WorkAreaTop]       SMALLINT      DEFAULT (NULL) NULL,
    [WorkAreaLeft]      SMALLINT      DEFAULT (NULL) NULL,
    [WorkAreaWidth]     SMALLINT      DEFAULT (NULL) NULL,
    [WorkAreaHeight]    SMALLINT      DEFAULT (NULL) NULL,
    [BtnCloseTop]       SMALLINT      DEFAULT (NULL) NULL,
    [BtnCloseLeft]      SMALLINT      DEFAULT (NULL) NULL,
    [FaceImage]         VARCHAR (250) DEFAULT (NULL) NULL,
    [Description]       VARCHAR (500) DEFAULT (NULL) NULL,
    [BasePrice]         INT           DEFAULT (NULL) NULL,
    [OwnerTimeout]      INT           DEFAULT (NULL) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKObjectsTypesParentID] FOREIGN KEY ([ParentID]) REFERENCES [dbo].[objects_types] ([ID])
);

