//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_requirement
    {
        public int ID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> MaterialObjectTypeID { get; set; }
        public Nullable<short> Quality { get; set; }
        public Nullable<short> Influence { get; set; }
        public Nullable<short> Quantity { get; set; }
        public short IsRegionItemRequired { get; set; }
    
        public virtual objects_types objects_types { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
