//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_possible_blueprints
    {
        public int ID { get; set; }
        public int RecipeID { get; set; }
        public int BaseRecipeID { get; set; }
    
        public virtual recipe recipe { get; set; }
        public virtual recipe recipe1 { get; set; }
    }
}
