//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skill_type()
        {
            this.recipes = new HashSet<recipe>();
            this.skill_type1 = new HashSet<skill_type>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<short> Group { get; set; }
        public string PrimaryStat { get; set; }
        public string SecondaryStat { get; set; }
        public Nullable<int> MasterMessageID { get; set; }
        public Nullable<int> GMMessageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe> recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill_type> skill_type1 { get; set; }
        public virtual skill_type skill_type2 { get; set; }
    }
}
